services:
  - type: web
    name: axis-v4
    runtime: image
    repo: https://github.com/viroda1/Axis-V4
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
